name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  AUTHOR_TESTING: 1
  AUTOMATED_TESTING: 1
  RELEASE_TESTING: 0 

jobs:
  continuous-integration:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        perl:
          - '5.20'
          - '5.22'
          - '5.24'
          - '5.26'
          - '5.28'
          - '5.30'
          - '5.32'
          - '5.34'
          - '5.36'
          - 'latest'
    name: Perl ${{ matrix.perl }} on ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: Perl version
        run: perl -V
      - name: Install Dist::Zilla
        run: cpanm --notest Dist::Zilla
      - name: Install Dist::Zilla::App::Command::installdeps
        run: Dist::Zilla::App::Command::installdeps
      - name: Install dependencies
        run: dzil installdeps --suggests --recommends
      - name: Test
        run: dzil test
      - name: Archive CPAN logs on Unix
        if: ${{ failure() && matrix.os != 'windows-latest' }}
        uses: actions/upload-artifact@v3
        with:
          name: cpan_log
          path: /home/runner/.cpanm/work/*/build.log
          retention-days: 5
